export const features = [
  "Pulse Check – quick mood check-ins with emoji tags and notes",
  "Moment Marker – create journal entries with optional date and Markdown",
  "Routine Tracker – log recurring routine activities",
  "Habit Tracker – create habits and log individual entries",
  "Task Tracker – manage tasks with priorities, due dates and drag‑to‑reorder",
  "Bulk Actions – select multiple tasks or habits to complete, delete or reschedule",
  "Recurring Tasks – automatically generate tasks on a schedule",
  "Calendar View – see events and entries on a calendar",
  "Global Search – press Ctrl/⌘+K to search across tasks, habits and entries",
  "Dark Mode – toggle between light and dark themes",
  "Customizable Layout – drag and drop dashboard widgets and navigation items",
  "Editable Mood Options – manage your own set of moods and routine items",
  "Routine Templates – create reusable routine item sets",
  "Journal Templates – save common prompts for new entries",
  "Recurring Task Quotas – limit how often recurring tasks are generated",
  "Analytics Dashboard – view aggregate stats on your productivity",
  "Due Date Index – faster `/tasks/due` queries via a database index on task due dates",
  "Task Filter Indexes – faster `/tasks` filtering via indexes on status, energy level and tags",
  "Offline Support – installable PWA with cached assets for offline use",
];
